---
  - id: yamltool  # yamllint disable-line rule:indentation
    name: YAML tool
    description: Validate and pretty-print YAML files.
    language: python
    entry: yt
    args: ["--in-place"]
    types: [yaml]
